# ec2/templates/lamp-server-tutorial.yml
AWSTemplateFormatVersion: "2010-09-09"
Description: LAMP server tutorial

Parameters:
  OperatingSystem:
    Type: String
    Description: Operating system name
    Default: AL2
    AllowedValues:
      - AL2
      - AL2013
    ConstraintDescription: must be either 'AL2' or 'AL2013'

  InstanceType:
    Type: String
    Description: EC2 instance type
    Default: t2.micro
    AllowedValues:
      - t2.micro
    ConstraintDescription: must be 't2.micro' only

  PublicKeyBody:
    Type: String
    Description: EC2 public key
    AllowedPattern: ssh-rsa .*
    ConstraintDescription: must be a valid RSA public key

  IngressCidr:
    Type: String
    Description: IP address for ingress
    Default: 0.0.0.0/0
    AllowedPattern: \d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/\d{1,2}
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x

  EC2InstanceName:
    Type: String
    Description: Name for the EC2 instance
    Default: LAMPServerTutorial

Mappings:
  RegionOS2AMI:
    ap-northeast-1:
      AL2: ami-030cf0a1edb8636ab
      AL2013: ami-067871d950411e643

Resources:
  SSHKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName:
        Fn::Sub: ${AWS::StackName}-keypair
      PublicKeyMaterial:
        Ref: PublicKeyBody

  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Web security group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp:
            Ref: IngressCidr
        - IpProtocol: tcp
          FromPort: 443
          ToPort: 443
          CidrIp:
            Ref: IngressCidr
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp:
            Ref: IngressCidr

  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: Service role for EC2 instance
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: EC2InstanceRole

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Fn::FindInMap:
          - RegionOS2AMI
          - Ref: AWS::Region
          - Ref: OperatingSystem
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: SSHKeyPair
      SecurityGroups:
        - Ref: WebSecurityGroup
      Tags:
        - Key: Name
          Value:
            Ref: EC2InstanceName
      IamInstanceProfile:
        Ref: EC2InstanceProfile
