# ec2/templates/windows-rdp.yml
AWSTemplateFormatVersion: "2010-09-09"
Description: RDP to Windows instance

Parameters:
  SshCidrIp:
    Type: String
    Description: SSH CIDR IP block
    AllowedPattern: \d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/\d{1,2}
    ConstraintDescription: must be a valid CIDR block of the form x.x.x.x/x

  PublicKeyBody:
    Type: String
    Description: EC2 public key
    AllowedPattern: ssh-rsa .*
    ConstraintDescription: must be a valid RSA public key

  WindowsServerAMI:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Description: Windows Server AMI ID
    Default: /aws/service/ami-windows-latest/Windows_Server-2022-English-Full-Base

  InstanceType:
    Type: String
    Description: Instance type
    Default: t2.micro

  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID
    Default: vpc-01d5cfd2cad5314f1

  SubnetIds:
    Type: List<AWS::EC2::Subnet::Id>
    Description: Subnet IDs
    Default: subnet-00ee516fa04d610fe,subnet-0c99e2001f0ae6c0a

Resources:
  KeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName:
        Fn::Sub: ${AWS::StackName}-KeyPair
      PublicKeyMaterial:
        Ref: PublicKeyBody

  WindowsSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName:
        Fn::Sub: ${AWS::StackName}-WindowsSecurityGroup
      GroupDescription: Dicrectory service EC2 instance security group
      VpcId:
        Ref: VpcId
      SecurityGroupIngress:
        - Description: Remote Desktop
          IpProtocol: tcp
          FromPort: 3389
          ToPort: 3389
          CidrIp:
            Ref: SshCidrIp
      Tags:
        - Key: Name
          Value: WindowsSecurityGroup

  WindowsInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${AWS::StackName}-WindowsInstanceRole-${AWS::Region}
      Description: Service role for Directory service EC2 instance
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                Fn::Sub: ec2.${AWS::URLSuffix}
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore

  WindowsInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName:
        Fn::Sub: ${AWS::StackName}-WindowsInstanceProfile-${AWS::Region}
      Roles:
        - Ref: WindowsInstanceRole

  WindowsInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Ref: WindowsServerAMI
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: KeyPair
      IamInstanceProfile:
        Ref: WindowsInstanceProfile
      SecurityGroupIds:
        - Ref: WindowsSecurityGroup
      SubnetId:
        Fn::Select:
          - 0
          - Ref: SubnetIds
      Tags:
        - Key: Name
          Value: WindowsInstance
