AWSTemplateFormatVersion: "2010-09-09"
Description: Infra stack

Parameters:
  # Generic parameters
  AccountAlias:
    Type: String
    Description: Account alias name
    Default: hryssmz

  ManagementAccountId:
    Type: String
    Description: Management account ID
    Default: "512667299293"

  # SSO parameters
  IdentityStoreId:
    Type: String
    Description: Identity store ID
    Default: d-95676dc1f8

  # Organizations parameters
  DelegatedAdminAccountIds:
    Type: CommaDelimitedList
    Description: List of delegated admin account IDs
    Default: "343562251096"

Rules:
  TestTokyo:
    Assertions:
      - AssertDescription: Only ap-northeast-1 is allowed
        Assert:
          Fn::Equals:
            - ap-northeast-1
            - Ref: AWS::Region

  TestManagementAccount:
    Assertions:
      - AssertDescription: Only management account is allowed
        Assert:
          Fn::Equals:
            - Ref: ManagementAccountId
            - Ref: AWS::AccountId

Resources:
  # S3 resources
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Ref: AccountAlias
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  # IAM resources
  CodeCommitUser:
    Type: AWS::IAM::User
    Properties:
      UserName: CodeCommitUser
      ManagedPolicyArns:
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/AWSCodeCommitPowerUser

  # Organizations resources
  OrganizationsResourcePolicy:
    Type: AWS::Organizations::ResourcePolicy
    Properties:
      Content:
        Version: "2012-10-17"
        Statement:
          - Sid: OrganizationsReadPermissions
            Effect: Allow
            Principal:
              AWS:
                Ref: DelegatedAdminAccountIds
            Action:
              - organizations:Describe*
              - organizations:List*
            Resource: "*"
          - Sid: OrganizationsWritePermissions
            Effect: Allow
            Principal:
              AWS:
                Ref: DelegatedAdminAccountIds
            Action:
              - organizations:AttachPolicy
              - organizations:CreatePolicy
              - organizations:DeletePolicy
              - organizations:DetachPolicy
              - organizations:DisablePolicyType
              - organizations:EnablePolicyType
              - organizations:TagResource
              - organizations:UntagResource
              - organizations:UpdatePolicy
            Resource: "*"

Outputs:
  # SSO outputs
  SSOStartURL:
    Description: URL for AWS access portal
    Value:
      Fn::Sub: https://${IdentityStoreId}.awsapps.com/start
