AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: Virginia infra stack

Parameters:
  DomainName:
    Type: String
    Description: Hosted zone domain name
    Default: hryssmz.click

Rules:
  TestVirginia:
    Assertions:
      - AssertDescription: Only us-east-1 is allowed
        Assert:
          Fn::Equals:
            - us-east-1
            - Ref: AWS::Region

Resources:
  # Route 53
  HostedZone:
    Type: AWS::Route53::HostedZone
    Properties:
      Name:
        Ref: DomainName
      HostedZoneConfig:
        Comment: My root hosted zone

Outputs:
  HostedZoneId:
    Description: Hosted zone ID
    Value:
      Ref: HostedZone
