version: 0.2
phases:
  pre_build:
    commands:
      - REGISTRY_URI=$(echo ${REPOSITORY_URI} | cut -d/ -f1)
      - aws ecr get-login-password --region ${REGION} | docker login --username AWS --password-stdin ${REGISTRY_URI}
  build:
    commands:
      - docker image build -t ${REPOSITORY_URI}:latest .
      - docker image push ${REPOSITORY_URI}:latest
