openapi: "3.0.1"
servers:
  - url: https://{restApiId}.execute-api.{region}.amazonaws.com/{basePath}
    variables:
      restApiId:
        default: hxhhn2xxx4
      region:
        default: ap-northeast-1
      basePath:
        default: dev
info:
  title: My REST API
  version: "1.0"
paths:
  /:
    post:
      operationId: PostRoot
      tags:
        - Root
      requestBody:
        description: POST / request body
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PostRootRequest"
      responses:
        "200":
          description: 200 OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PostRootResponse"
              examples:
                example1:
                  value:
                    message: Hello World!
          headers:
            Access-Control-Allow-Origin:
              $ref: "#/components/headers/Access-Control-Allow-Origin"
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${PostRootFunction.Arn}/invocations
        httpMethod: POST
components:
  headers:
    Access-Control-Allow-Origin:
      description: Response header for CORS support
      schema:
        type: string
  schemas:
    PostRootRequest:
      description: Request body for POST /
      type: object
    PostRootResponse:
      description: Response body for GET /
      type: object
      required:
        - message
      properties:
        message:
          type: string
