# cognito/templates/amplify-auth.yml
AWSTemplateFormatVersion: "2010-09-09"
Description: Amplify auth

Resources:
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      AutoVerifiedAttributes:
        - email
      MfaConfiguration: "OFF"
      Policies:
        PasswordPolicy:
          MinimumLength: 8
          RequireLowercase: false
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
      Schema:
        - Mutable: true
          Name: email
          Required: true
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:
          - email
      UsernameConfiguration:
        CaseSensitive: false
      VerificationMessageTemplate:
        DefaultEmailOption: CONFIRM_WITH_CODE
        EmailMessage: Your verification code is {####}
        EmailSubject: Your verification code

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId:
        Ref: UserPool
      GenerateSecret: false
      RefreshTokenValidity: 30
      TokenValidityUnits:
        RefreshToken: days

  UserPoolClientWeb:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      UserPoolId:
        Ref: UserPool
      RefreshTokenValidity: 30
      TokenValidityUnits:
        RefreshToken: days

  IdentityPool:
    Type: AWS::Cognito::IdentityPool
    Properties:
      AllowUnauthenticatedIdentities: false
      CognitoIdentityProviders:
        - ClientId:
            Ref: UserPoolClient
          ProviderName:
            Fn::Sub: cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}
        - ClientId:
            Ref: UserPoolClientWeb
          ProviderName:
            Fn::Sub: cognito-idp.${AWS::Region}.amazonaws.com/${UserPool}

Outputs:
  UserPoolId:
    Value:
      Ref: UserPool
  UserPoolArn:
    Value:
      Fn::GetAtt: UserPool.Arn
