# cognito/templates/first-user-pool.yml
AWSTemplateFormatVersion: "2010-09-09"
Description: My first Cognito User Pool

Parameters:
  UserPoolDomainPrefix:
    Type: String
    Description: User pool domain prefix
    Default: hryssmz

  DefaultRedirectURI:
    Type: String
    Description: Default redirect URI
    Default: http://localhost

Resources:
  SmsSenderPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName:
        Fn::Sub: ${AWS::StackName}-SmsSenderPolicy-${AWS::Region}
      Description: Execution policy for sending SMS
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - sns:Publish
            Resource: "*"

  SmsSenderRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${AWS::StackName}-SmsSenderRole-${AWS::Region}
      Description: Service role for sending SMS
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                Fn::Sub: cognito-idp.${AWS::URLSuffix}
            Action:
              - sts:AssumeRole
            Condition:
              StringEquals:
                aws:SourceAccount:
                  Ref: AWS::AccountId
              ArnLike:
                aws:SourceArn:
                  Fn::Sub: arn:${AWS::Partition}:cognito-idp:${AWS::Region}:${AWS::AccountId}:userpool/*
      ManagedPolicyArns:
        - Ref: SmsSenderPolicy

  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName:
        Fn::Sub: ${AWS::StackName}-UserPool
      AliasAttributes:
        - email
      UsernameConfiguration:
        CaseSensitive: false
      Policies:
        PasswordPolicy:
          MinimumLength: 6
          RequireNumbers: false
          RequireSymbols: false
          RequireUppercase: false
          RequireLowercase: false
          TemporaryPasswordValidityDays: 7
      MfaConfiguration: OPTIONAL
      EnabledMfas:
        - SMS_MFA
        - SOFTWARE_TOKEN_MFA
      AccountRecoverySetting:
        RecoveryMechanisms:
          - Name: verified_email
            Priority: 1
          - Name: verified_phone_number
            Priority: 2
      AdminCreateUserConfig:
        AllowAdminCreateUserOnly: false
      AutoVerifiedAttributes:
        - email
        - phone_number
      UserAttributeUpdateSettings:
        AttributesRequireVerificationBeforeUpdate:
          - email
          - phone_number
      Schema:
        - Name: email
          Required: true
          Mutable: true
        - Name: given_name
          Required: true
          Mutable: true
        - Name: family_name
          Required: true
          Mutable: true
        - Name: phone_number
          Required: false
          Mutable: true
      EmailConfiguration:
        EmailSendingAccount: COGNITO_DEFAULT
      SmsConfiguration:
        ExternalId: KeyboardCat
        SnsCallerArn:
          Fn::GetAtt: SmsSenderRole.Arn
        SnsRegion:
          Ref: AWS::Region

  UserPoolDomain:
    Type: AWS::Cognito::UserPoolDomain
    Properties:
      UserPoolId:
        Ref: UserPool
      Domain:
        Ref: UserPoolDomainPrefix

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName:
        Fn::Sub: ${AWS::StackName}-UserPoolClient
      UserPoolId:
        Ref: UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_ADMIN_USER_PASSWORD_AUTH
        - ALLOW_CUSTOM_AUTH
        - ALLOW_USER_PASSWORD_AUTH
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      AuthSessionValidity: 3
      RefreshTokenValidity: 30
      AccessTokenValidity: 3
      IdTokenValidity: 3
      TokenValidityUnits:
        RefreshToken: days
        AccessToken: hours
        IdToken: hours
      EnableTokenRevocation: true
      PreventUserExistenceErrors: ENABLED
      EnablePropagateAdditionalUserContextData: false
      CallbackURLs:
        - Ref: DefaultRedirectURI
      DefaultRedirectURI:
        Ref: DefaultRedirectURI
      SupportedIdentityProviders:
        - COGNITO
      AllowedOAuthFlows:
        - code
        - implicit
      AllowedOAuthFlowsUserPoolClient: true
      AllowedOAuthScopes:
        - email
        - phone
        - openid
      ReadAttributes:
        - email
        - email_verified
        - family_name
        - given_name
        - phone_number
        - phone_number_verified
      WriteAttributes:
        - email
        - family_name
        - given_name
        - phone_number

Outputs:
  HostedUIUrl:
    Description: URL for hosted UI
    Value:
      Fn::Sub: https://${UserPoolDomainPrefix}.auth.${AWS::Region}.amazoncognito.com/oauth2/authorize?client_id=${UserPoolClient}&response_type=code&redirect_uri=${DefaultRedirectURI}
