openapi: "3.0.1"
info:
  title: My REST API
  version: "1.0"
servers:
  - url: https://{restApiId}.execute-api.{region}.amazonaws.com/{basePath}
    variables:
      restApiId:
        default: wavq7mejfi
      region:
        default: ap-northeast-1
      basePath:
        default: dev
security:
  - CognitoAuthorizer:
      - aws.cognito.signin.user.admin
paths:
  /:
    get:
      operationId: GetRoot
      tags:
        - GetRoot
      responses:
        "200":
          description: 200 OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetRootResponse"
              examples:
                example1:
                  value:
                    origin_jti: ab1aaac1-c343-4e71-9901-30b6381a5d0a
                    sub: 17740ae8-7081-70b2-93a0-1577f2e611ab
                    event_id: 5befc155-f385-49f6-9e5f-cad3f9884d43
                    token_use: access
                    scope: aws.cognito.signin.user.admin
                    auth_time: "1693502522"
                    iss: https://cognito-idp.ap-northeast-1.amazonaws.com/ap-northeast-1_yNbC6Cny6
                    exp: Thu Aug 31 18:22:02 UTC 2023
                    iat: Thu Aug 31 17:22:02 UTC 2023
                    client_id: 4dvqs9hmkv74cs6upkhshr598a
                    jti: de4befe6-6ef4-4b60-8f0a-f6b89f36e4f6
                    username: cognitouser
          headers:
            Access-Control-Allow-Origin:
              description: Response header for CORS support
              schema:
                type: string
      x-amazon-apigateway-integration:
        type: aws_proxy
        uri:
          Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GetRootFunction.Arn}/invocations
        httpMethod: POST
components:
  securitySchemes:
    CognitoAuthorizer:
      type: apiKey
      name: Authorization
      in: header
      x-amazon-apigateway-authtype: cognito_user_pools
      x-amazon-apigateway-authorizer:
        type: cognito_user_pools
        providerARNs:
          - Fn::GetAtt: UserPool.Arn
  schemas:
    GetRootResponse:
      description: Response body for GET /
      type: object
