# sns/templates/getting-started-sns.yml
AWSTemplateFormatVersion: "2010-09-09"
Description: Getting started with Amazon SNS
Parameters:
  MyEmail:
    Type: String
Resources:
  MyTopic:
    Type: AWS::SNS::Topic
    Properties:
      FifoTopic: false
      Subscription:
        - Protocol: email
          Endpoint:
            Ref: MyEmail
