# dynamodb/templates/ddb-stream-kinesis.yml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: DynamoDB Stream with Kinesis Data Stream

Resources:
  SimpleTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName:
        Fn::Sub: ${AWS::StackName}-SimpleTable
      AttributeDefinitions:
        - AttributeName: Id
          AttributeType: S
      KeySchema:
        - AttributeName: Id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      KinesisStreamSpecification:
        StreamArn:
          Fn::GetAtt: KinesisStream.Arn

  KinesisStream:
    Type: AWS::Kinesis::Stream
    Properties:
      Name:
        Fn::Sub: ${AWS::StackName}-KinesisStream
      ShardCount: 1
      StreamModeDetails:
        StreamMode: PROVISIONED

  ConsumerFunctionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName:
        Fn::Sub: ${AWS::StackName}-ConsumerFunctionPolicy-${AWS::Region}
      Description: Policy for ConsumerFunction
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - kinesis:GetRecords
              - kinesis:GetShardIterator
              - kinesis:DescribeStream
              - kinesis:ListShards
            Resource:
              - Fn::GetAtt: KinesisStream.Arn
          - Effect: Allow
            Action:
              - kinesis:ListStreams
            Resource: "*"

  ConsumerFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${AWS::StackName}-ConsumerFunctionRole-${AWS::Region}
      Description: Service role for ConsumerFunction
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                Fn::Sub: lambda.${AWS::URLSuffix}
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - Ref: ConsumerFunctionPolicy

  ConsumerFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${AWS::StackName}-ConsumerFunction

  ConsumerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${AWS::StackName}-ConsumerFunction
      Description: Consumer function
      Role:
        Fn::GetAtt: ConsumerFunctionRole.Arn
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - arm64
      LoggingConfig:
        LogGroup:
          Ref: ConsumerFunctionLogGroup
      Events:
        KinesisEvent:
          Type: Kinesis
          Properties:
            Stream:
              Fn::GetAtt: KinesisStream.Arn
            StartingPosition: LATEST
            BatchSize: 3
      InlineCode: |
        exports.handler = async event => {
          const records = event.Records.map(({ kinesis }) => kinesis).map(
            ({ partitionKey, data }) => ({
              partitionKey,
              data: Buffer.from(data, "base64").toString(),
            })
          );
          console.log(JSON.stringify(records, null, 2));
          return records;
        };

  PutItemFunctionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName:
        Fn::Sub: ${AWS::StackName}-PutItemFunctionPolicy-${AWS::Region}
      Description: Policy for PutItemFunction
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - dynamodb:PutItem
            Resource:
              - Fn::GetAtt: SimpleTable.Arn

  PutItemFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${AWS::StackName}-PutItemFunctionRole-${AWS::Region}
      Description: Service role for PutItemFunction
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                Fn::Sub: lambda.${AWS::URLSuffix}
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - Ref: PutItemFunctionPolicy

  PutItemFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${AWS::StackName}-PutItemFunction

  PutItemFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${AWS::StackName}-PutItemFunction
      Description: Producer function
      Role:
        Fn::GetAtt: PutItemFunctionRole.Arn
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - arm64
      LoggingConfig:
        LogGroup:
          Ref: PutItemFunctionLogGroup
      Environment:
        Variables:
          TABLE_NAME:
            Ref: SimpleTable
      InlineCode: |
        const { randomUUID } = require("crypto");
        const { DynamoDBClient } = require("@aws-sdk/client-dynamodb");
        const { DynamoDBDocumentClient, PutCommand } = require("@aws-sdk/lib-dynamodb");

        exports.handler = async () => {
          const client = DynamoDBDocumentClient.from(new DynamoDBClient());
          const command = new PutCommand({
            TableName: process.env.TABLE_NAME,
            Item: { Id: randomUUID() },
          });
          const { Attributes } = await client.send(command);
          return Attributes;
        };
