# dynamodb/templates/provisioned-table.yml
AWSTemplateFormatVersion: "2010-09-09"
Description: Provisioned table

Resources:
  MusicTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: Artist
          AttributeType: S
        - AttributeName: SongTitle
          AttributeType: S
      KeySchema:
        - AttributeName: Artist
          KeyType: HASH
        - AttributeName: SongTitle
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

Outputs:
  MusicTable:
    Value:
      Ref: MusicTable
