# vpc/templates/traffic-mirror.yml
AWSTemplateFormatVersion: "2010-09-09"
Description: Traffic mirroring

Parameters:
  VPCCidr:
    Type: String
    Description: VPC CIDR
    Default: 172.20.0.0/16

  SubnetCidrs:
    Type: CommaDelimitedList
    Description: Subnet CIDRs
    Default: 172.20.0.0/20,172.20.16.0/20

  ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Description: EC2 image ID
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64

  InstanceType:
    Type: String
    Description: EC2 instance type
    Default: t2.micro

Resources:
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: VPCCidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC

  Subnet0:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock:
        Fn::Select:
          - 0
          - Ref: SubnetCidrs
      VpcId:
        Ref: VPC
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Subnet0

  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock:
        Fn::Select:
          - 1
          - Ref: SubnetCidrs
      VpcId:
        Ref: VPC
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: ""
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Subnet1

  RouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC
      Tags:
        - Key: Name
          Value: RouteTable

  Subnet0RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: Subnet0
      RouteTableId:
        Ref: RouteTable

  Subnet1RouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: Subnet1
      RouteTableId:
        Ref: RouteTable

  InternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: InternetGateway

  InternetGatewayAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: VPC
      InternetGatewayId:
        Ref: InternetGateway

  InternetRoute:
    Type: AWS::EC2::Route
    DependsOn: InternetGatewayAttachment
    Properties:
      RouteTableId:
        Ref: RouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway

  # Traffic mirror
  TargetSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName:
        Fn::Sub: ${AWS::StackName}-TargetSecurityGroup
      GroupDescription: Target security group
      VpcId:
        Ref: VPC
      SecurityGroupIngress:
        - Description: Traffic mirror inbound rule
          IpProtocol: udp
          FromPort: 4789
          ToPort: 4789
          CidrIp: 0.0.0.0/0
        - Description: PostgreSQL inbound rule
          IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp:
            Fn::GetAtt: VPC.CidrBlock
      Tags:
        - Key: Name
          Value: TargetSecurityGroup

  TargetNetworkInterface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: Target network interface for traffic mirroring
      InterfaceType: interface
      GroupSet:
        - Ref: TargetSecurityGroup
      SubnetId:
        Ref: Subnet0
      Tags:
        - Key: Name
          Value: TargetNetworkInterface

  SourceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName:
        Fn::Sub: ${AWS::StackName}-SourceSecurityGroup
      GroupDescription: Source security group
      VpcId:
        Ref: VPC
      Tags:
        - Key: Name
          Value: SourceSecurityGroup

  SourceNetworkInterface:
    Type: AWS::EC2::NetworkInterface
    Properties:
      Description: Source network interface for traffic mirroring
      InterfaceType: interface
      GroupSet:
        - Ref: SourceSecurityGroup
      SubnetId:
        Ref: Subnet1
      Tags:
        - Key: Name
          Value: SourceNetworkInterface

  TrafficMirrorFilter:
    Type: AWS::EC2::TrafficMirrorFilter
    Properties:
      Description: Traffic mirror filter
      Tags:
        - Key: Name
          Value: TrafficMirrorFilter

  TrafficMirrorFilterRule:
    Type: AWS::EC2::TrafficMirrorFilterRule
    Properties:
      Description: Traffic mirror filter rule
      TrafficMirrorFilterId:
        Ref: TrafficMirrorFilter
      RuleNumber: 10
      Protocol: 6
      SourceCidrBlock:
        Fn::GetAtt: VPC.CidrBlock
      DestinationCidrBlock:
        Fn::GetAtt: VPC.CidrBlock
      TrafficDirection: egress
      RuleAction: accept

  TrafficMirrorTarget:
    Type: AWS::EC2::TrafficMirrorTarget
    DependsOn: TargetInstance
    Properties:
      Description: Traffic mirror target
      NetworkInterfaceId:
        Ref: TargetNetworkInterface
      Tags:
        - Key: Name
          Value: TrafficMirrorTarget

  TrafficMirrorSession:
    Type: AWS::EC2::TrafficMirrorSession
    DependsOn: EC2Instance
    Properties:
      Description: Traffic mirror session
      SessionNumber: 10
      TrafficMirrorFilterId:
        Ref: TrafficMirrorFilter
      NetworkInterfaceId:
        Ref: SourceNetworkInterface
      TrafficMirrorTargetId:
        Ref: TrafficMirrorTarget
      Tags:
        - Key: Name
          Value: TrafficMirrorSession

  # EC2
  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${AWS::StackName}-EC2InstanceRole-${AWS::Region}
      Description: Service role for EC2 instance
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                Fn::Sub: ec2.${AWS::URLSuffix}
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/AmazonSSMManagedInstanceCore

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      InstanceProfileName:
        Fn::Sub: ${AWS::StackName}-EC2InstanceProfile-${AWS::Region}
      Roles:
        - Ref: EC2InstanceRole

  EC2Instance:
    Type: AWS::EC2::Instance
    Metadata:
      AWS::CloudFormation::Init:
        config:
          files:
            /usr/local/bin/db-login.sh:
              content:
                Fn::Sub: |
                  #!/bin/sh
                  psql -d postgresql://postgres:postgres@${DBInstance.PrivateDnsName}/$1
              mode: "000755"
    Properties:
      ImageId:
        Ref: ImageId
      InstanceType: m4.large
      IamInstanceProfile:
        Ref: EC2InstanceProfile
      NetworkInterfaces:
        - DeviceIndex: 0
          Description: Source network interface for traffic mirroring
          NetworkInterfaceId:
            Ref: SourceNetworkInterface
      UserData:
        Fn::Base64:
          Fn::Sub: |
            #!/bin/sh
            dnf update -y
            dnf install -y postgresql15
            /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2Instance --region ${AWS::Region}
      Tags:
        - Key: Name
          Value: EC2Instance

  TargetInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Ref: ImageId
      InstanceType:
        Ref: InstanceType
      IamInstanceProfile:
        Ref: EC2InstanceProfile
      NetworkInterfaces:
        - DeviceIndex: 0
          Description: Target network interface for traffic mirroring
          NetworkInterfaceId:
            Ref: TargetNetworkInterface
      UserData:
        Fn::Base64:
          Fn::Sub: |
            #!/bin/sh
            dnf update -y
            dnf install -y postgresql15-server

            sudo -i -u postgres /bin/sh - <<\EOF
            postgresql-setup --initdb
            echo "local all all peer" > /var/lib/pgsql/data/pg_hba.conf
            echo "host all all 0.0.0.0/0 md5" >> /var/lib/pgsql/data/pg_hba.conf
            echo "listen_addresses = '*'" >> /var/lib/pgsql/data/postgresql.conf
            EOF
            systemctl enable postgresql
            systemctl start postgresql
            sudo -i -u postgres psql -c "ALTER ROLE postgres WITH PASSWORD 'postgres';"
      Tags:
        - Key: Name
          Value: TargetInstance

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName:
        Fn::Sub: ${AWS::StackName}-DBSecurityGroup
      GroupDescription: DB security group
      VpcId:
        Ref: VPC
      SecurityGroupIngress:
        - Description: ICMP inbound rule
          IpProtocol: icmp
          FromPort: -1
          ToPort: -1
          CidrIp:
            Fn::GetAtt: VPC.CidrBlock
        - Description: PostgreSQL inbound rule
          IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          CidrIp:
            Fn::GetAtt: VPC.CidrBlock
      Tags:
        - Key: Name
          Value: DBSecurityGroup

  DBInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Ref: ImageId
      InstanceType:
        Ref: InstanceType
      IamInstanceProfile:
        Ref: EC2InstanceProfile
      SecurityGroupIds:
        - Ref: DBSecurityGroup
      SubnetId:
        Ref: Subnet0
      UserData:
        Fn::Base64:
          Fn::Sub: |
            #!/bin/sh
            dnf update -y
            dnf install -y postgresql15-server

            sudo -i -u postgres /bin/sh - <<\EOF
            postgresql-setup --initdb
            echo "local all all peer" > /var/lib/pgsql/data/pg_hba.conf
            echo "host all all 0.0.0.0/0 md5" >> /var/lib/pgsql/data/pg_hba.conf
            echo "listen_addresses = '*'" >> /var/lib/pgsql/data/postgresql.conf
            EOF
            systemctl enable postgresql
            systemctl start postgresql
            sudo -i -u postgres psql -c "ALTER ROLE postgres WITH PASSWORD 'postgres';"
      Tags:
        - Key: Name
          Value: DBInstance
