# vpc/templates/transit-gateway.yml
AWSTemplateFormatVersion: "2010-09-09"
Description: Getting started with transit gateways

Parameters:
  SshCidrIp:
    Type: String
    Description: SSH CIDR IP block
    AllowedPattern: \d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/\d{1,2}
    ConstraintDescription: must be a valid CIDR block of the form x.x.x.x/x

  PublicKeyBody:
    Type: String
    Description: EC2 public key
    AllowedPattern: ssh-rsa .*
    ConstraintDescription: must be a valid RSA public key

  TGWCidr:
    Type: String
    Description: Transit gateway CIDR
    Default: 172.20.0.0/16

  VPC1Cidr:
    Type: String
    Description: VPC 1 CIDR
    Default: 172.20.0.0/17

  Subnet1Cidr:
    Type: String
    Description: Subnet 1 CIDR
    Default: 172.20.0.0/20

  PrivateSubnet1Cidr:
    Type: String
    Description: Private subnet 1 CIDR
    Default: 172.20.64.0/20

  VPC2Cidr:
    Type: String
    Description: VPC 2 CIDR
    Default: 172.20.128.0/17

  Subnet2Cidr:
    Type: String
    Description: Subnet 2 CIDR
    Default: 172.20.128.0/20

  PrivateSubnet2Cidr:
    Type: String
    Description: Private subnet 2 CIDR
    Default: 172.20.192.0/20

  ImageId:
    Type: AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>
    Description: EC2 image ID
    Default: /aws/service/ami-amazon-linux-latest/al2023-ami-kernel-default-x86_64

  InstanceType:
    Type: String
    Description: EC2 instance type
    Default: t2.micro

Resources:
  # VPC
  VPC1:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: VPC1Cidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC1

  Subnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock:
        Ref: Subnet1Cidr
      VpcId:
        Ref: VPC1
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Subnet1

  RouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC1
      Tags:
        - Key: Name
          Value: RouteTable1

  Subnet1RouteTable1Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: Subnet1
      RouteTableId:
        Ref: RouteTable1

  InternetGateway1:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: InternetGateway1

  InternetGateway1Attachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: VPC1
      InternetGatewayId:
        Ref: InternetGateway1

  InternetRoute1:
    Type: AWS::EC2::Route
    DependsOn: InternetGateway1Attachment
    Properties:
      RouteTableId:
        Ref: RouteTable1
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway1

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock:
        Ref: PrivateSubnet1Cidr
      VpcId:
        Ref: VPC1
      Tags:
        - Key: Name
          Value: PrivateSubnet1

  PrivateRouteTable1:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC1
      Tags:
        - Key: Name
          Value: PrivateRouteTable1

  PrivateSubnet1PrivateRouteTable1Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PrivateSubnet1
      RouteTableId:
        Ref: PrivateRouteTable1

  # VPC2
  VPC2:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock:
        Ref: VPC2Cidr
      EnableDnsSupport: true
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: VPC2

  Subnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock:
        Ref: Subnet2Cidr
      VpcId:
        Ref: VPC2
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: Subnet2

  RouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC2
      Tags:
        - Key: Name
          Value: RouteTable2

  Subnet2RouteTable2Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: Subnet2
      RouteTableId:
        Ref: RouteTable2

  InternetGateway2:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: InternetGateway2

  InternetGateway2Attachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
        Ref: VPC2
      InternetGatewayId:
        Ref: InternetGateway2

  InternetRoute2:
    Type: AWS::EC2::Route
    DependsOn: InternetGateway1Attachment
    Properties:
      RouteTableId:
        Ref: RouteTable2
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId:
        Ref: InternetGateway2

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock:
        Ref: PrivateSubnet2Cidr
      VpcId:
        Ref: VPC2
      Tags:
        - Key: Name
          Value: PrivateSubnet2

  PrivateRouteTable2:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Ref: VPC2
      Tags:
        - Key: Name
          Value: PrivateRouteTable2

  PrivateSubnet2PrivateRouteTable2Association:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PrivateSubnet2
      RouteTableId:
        Ref: PrivateRouteTable2

  # Transit Gateway
  TransitGateway:
    Type: AWS::EC2::TransitGateway
    Properties:
      AmazonSideAsn: 64512
      Description: Transit gateway
      DnsSupport: enable
      VpnEcmpSupport: enable
      DefaultRouteTableAssociation: enable
      DefaultRouteTablePropagation: enable
      MulticastSupport: disable
      AutoAcceptSharedAttachments: disable
      Tags:
        - Key: Name
          Value: TransitGateway

  PrivateSubnet1TgwAttachment:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties:
      TransitGatewayId:
        Ref: TransitGateway
      VpcId:
        Ref: VPC1
      SubnetIds:
        - Ref: PrivateSubnet1
      Options:
        DnsSupport: enable
        Ipv6Support: disable
        ApplianceModeSupport: disable
      Tags:
        - Key: Name
          Value: PrivateSubnet1TgwAttachment

  PrivateSubnet2TgwAttachment:
    Type: AWS::EC2::TransitGatewayAttachment
    Properties:
      TransitGatewayId:
        Ref: TransitGateway
      VpcId:
        Ref: VPC2
      SubnetIds:
        - Ref: PrivateSubnet2
      Options:
        DnsSupport: enable
        Ipv6Support: disable
        ApplianceModeSupport: disable
      Tags:
        - Key: Name
          Value: PrivateSubnet2TgwAttachment

  PrivateSubnet1TgwRoute:
    Type: AWS::EC2::Route
    DependsOn: PrivateSubnet1TgwAttachment
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable1
      DestinationCidrBlock:
        Ref: TGWCidr
      TransitGatewayId:
        Ref: TransitGateway

  PrivateSubnet2TgwRoute:
    Type: AWS::EC2::Route
    DependsOn: PrivateSubnet2TgwAttachment
    Properties:
      RouteTableId:
        Ref: PrivateRouteTable2
      DestinationCidrBlock:
        Ref: TGWCidr
      TransitGatewayId:
        Ref: TransitGateway

  # EC2
  SSHKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName:
        Fn::Sub: ${AWS::StackName}-SSHKeyPair
      PublicKeyMaterial:
        Ref: PublicKeyBody

  BastionSecurityGroup1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName:
        Fn::Sub: ${AWS::StackName}-BastionSecurityGroup1
      GroupDescription: Bastion instances security group 1
      VpcId:
        Ref: VPC1
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp:
            Ref: SshCidrIp
      Tags:
        - Key: Name
          Value: BastionSecurityGroup1

  PrivateSecurityGroup1:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName:
        Fn::Sub: ${AWS::StackName}-PrivateSecurityGroup1
      GroupDescription: Private instances security group 1
      VpcId:
        Ref: VPC1
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp:
            Ref: TGWCidr
      Tags:
        - Key: Name
          Value: PrivateSecurityGroup1

  BastionInstance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Ref: ImageId
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: SSHKeyPair
      SecurityGroupIds:
        - Ref: BastionSecurityGroup1
      SubnetId:
        Ref: Subnet1
      Tags:
        - Key: Name
          Value: BastionInstance1

  PrivateInstance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Ref: ImageId
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: SSHKeyPair
      SecurityGroupIds:
        - Ref: PrivateSecurityGroup1
      SubnetId:
        Ref: PrivateSubnet1
      Tags:
        - Key: Name
          Value: PrivateInstance1

  BastionSecurityGroup2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName:
        Fn::Sub: ${AWS::StackName}-BastionSecurityGroup2
      GroupDescription: Bastion instances security group 2
      VpcId:
        Ref: VPC2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp:
            Ref: SshCidrIp
      Tags:
        - Key: Name
          Value: BastionSecurityGroup2

  PrivateSecurityGroup2:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName:
        Fn::Sub: ${AWS::StackName}-PrivateSecurityGroup
      GroupDescription: Private instances security group 2
      VpcId:
        Ref: VPC2
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp:
            Ref: TGWCidr
      Tags:
        - Key: Name
          Value: PrivateSecurityGroup2

  BastionInstance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Ref: ImageId
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: SSHKeyPair
      SecurityGroupIds:
        - Ref: BastionSecurityGroup2
      SubnetId:
        Ref: Subnet2
      Tags:
        - Key: Name
          Value: BastionInstance2

  PrivateInstance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Ref: ImageId
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: SSHKeyPair
      SecurityGroupIds:
        - Ref: PrivateSecurityGroup2
      SubnetId:
        Ref: PrivateSubnet2
      Tags:
        - Key: Name
          Value: PrivateInstance2
