AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: aws-sam-python CI/CD stack

Parameters:
  ProjectName:
    Type: String
    Description: Project name
    Default: aws-sam-python

  DeploymentBranch:
    Type: String
    Description: CodeCommit branch to deploy
    Default: main

  CodeBuildImage:
    Type: String
    Description: CodeBuild build environment image
    Default: aws/codebuild/amazonlinux2-x86_64-standard:4.0

  PackagedTemplatePath:
    Type: String
    Description: Path for the packaged CloudFormation template file
    Default: packaged-template.yml

  TemplateConfigurationPath:
    Type: String
    Description: Path for the CloudFormation template configuration file
    Default: template-configuration.json

Resources:
  # CodeCommit
  CodeCommitRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName:
        Ref: ProjectName
      RepositoryDescription:
        Fn::Sub: ${ProjectName} repository
      Triggers:
        - Name: DeploymentBranchUpdateTrigger
          DestinationArn:
            Ref: CodeCommitUpdateTopic
          Branches:
            - Ref: DeploymentBranch
          Events:
            - createReference
            - updateReference

  # S3
  ArtifactsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName:
        Fn::Sub: ${ProjectName}-artifacts-${AWS::Region}
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - BucketKeyEnabled: true
            ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

  # CloudFormation
  CloudFormationServiceRole:
    Type: AWS::IAM::Role
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      RoleName:
        Fn::Sub: ${ProjectName}-CloudFormationServiceRole-${AWS::Region}
      Description: Service role for CloudFormation
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: cloudformation.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/AdministratorAccess

  # CodeBuild
  CodeBuildExecutionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName:
        Fn::Sub: ${ProjectName}-CodeBuildExecutionPolicy-${AWS::Region}
      Description: Execution policy for CodeBuild projects
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: CloudWatchLogsAccess
            Effect: Allow
            Action:
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource:
              - Fn::Sub: arn:${AWS::Partition}:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/${ProjectName}-*:log-stream:*
          - Sid: ArtifactsBucketObjectsAccess
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:PutObject
            Resource:
              - Fn::Sub: ${ArtifactsBucket.Arn}/*
          - Sid: CodeBuildReportAccess
            Effect: Allow
            Action:
              - codebuild:BatchPutCodeCoverages
              - codebuild:BatchPutTestCases
              - codebuild:CreateReportGroup
              - codebuild:CreateReport
              - codebuild:UpdateReport
            Resource:
              - Fn::Sub: arn:${AWS::Partition}:codebuild:${AWS::Region}:${AWS::AccountId}:report-group/${ProjectName}-*
              - Fn::Sub: arn:${AWS::Partition}:codebuild:${AWS::Region}:${AWS::AccountId}:report/${ProjectName}-*:*
          - Sid: S3Access
            Effect: Allow
            Action:
              - s3:ListBucket
              - s3:PutObject
              - s3:DeleteObject
            Resource:
              - Fn::Sub: arn:${AWS::Partition}:s3:::${ProjectName}-*
              - Fn::Sub: arn:${AWS::Partition}:s3:::${ProjectName}-*/*
          - Sid: DynamoDBAccess
            Effect: Allow
            Action:
              - dynamodb:Scan
              - dynamodb:PutItem
              - dynamodb:DeleteItem
            Resource:
              - Fn::Sub: arn:${AWS::Partition}:dynamodb:${AWS::Region}:${AWS::AccountId}:table/${ProjectName}-*

  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${ProjectName}-CodeBuildServiceRole-${AWS::Region}
      Description: Service role for CodeBuild
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - Ref: CodeBuildExecutionPolicy

  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name:
        Fn::Sub: ${ProjectName}-BuildProject
      Description: Build project
      Source:
        Type: CODEPIPELINE
        BuildSpec:
          Fn::Sub: buildspecs/buildspec.yml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image:
          Ref: CodeBuildImage
        EnvironmentVariables:
          - Name: S3_BUCKET
            Value:
              Ref: ArtifactsBucket
          - Name: PACKAGED_TEMPALTE_PATH
            Value:
              Ref: PackagedTemplatePath
          - Name: TEMPLATE_CONFIGURATION_PATH
            Value:
              Ref: TemplateConfigurationPath
      TimeoutInMinutes: 5
      ServiceRole:
        Fn::GetAtt: CodeBuildServiceRole.Arn

  BuildProjectLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/codebuild/${BuildProject}

  UnitTestProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name:
        Fn::Sub: ${ProjectName}-UnitTestProject
      Description: Unit test project
      Source:
        Type: CODEPIPELINE
        BuildSpec:
          Fn::Sub: buildspecs/buildspec_ut.yml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image:
          Ref: CodeBuildImage
      TimeoutInMinutes: 5
      ServiceRole:
        Fn::GetAtt: CodeBuildServiceRole.Arn

  UnitTestCoverageReportGroup:
    Type: AWS::CodeBuild::ReportGroup
    Properties:
      Name:
        Fn::Sub: ${UnitTestProject}-coverage
      Type: CODE_COVERAGE
      DeleteReports: true
      ExportConfig:
        ExportConfigType: NO_EXPORT

  UnitTestReportGroup:
    Type: AWS::CodeBuild::ReportGroup
    Properties:
      Name:
        Fn::Sub: ${UnitTestProject}-test
      Type: TEST
      DeleteReports: true
      ExportConfig:
        ExportConfigType: NO_EXPORT

  UnitTestProjectLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/codebuild/${UnitTestProject}

  IntegrationTestProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name:
        Fn::Sub: ${ProjectName}-IntegrationTestProject
      Description: Integration test project
      Source:
        Type: CODEPIPELINE
        BuildSpec:
          Fn::Sub: buildspecs/buildspec_it.yml
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image:
          Ref: CodeBuildImage
      TimeoutInMinutes: 5
      ServiceRole:
        Fn::GetAtt: CodeBuildServiceRole.Arn

  IntegrationTestReportGroup:
    Type: AWS::CodeBuild::ReportGroup
    Properties:
      Name:
        Fn::Sub: ${IntegrationTestProject}-test
      Type: TEST
      DeleteReports: true
      ExportConfig:
        ExportConfigType: NO_EXPORT

  IntegrationTestProjectLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/codebuild/${IntegrationTestProject}

  # CodePipeline
  CodePipelineExecutionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName:
        Fn::Sub: ${ProjectName}-CodePipelineExecutionPolicy-${AWS::Region}
      Description: Execution policy for CodePipeline
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: ArtifactsBucketAccess
            Effect: Allow
            Action:
              - s3:GetBucketAcl
              - s3:GetBucketLocation
            Resource:
              - Fn::GetAtt: ArtifactsBucket.Arn
          - Sid: ArtifactsBucketObjectsAccess
            Effect: Allow
            Action:
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:PutObject
            Resource:
              - Fn::Sub: ${ArtifactsBucket.Arn}/*
          - Sid: CodeCommitAccess
            Effect: Allow
            Action:
              - codecommit:CancelUploadArchive
              - codecommit:GetBranch
              - codecommit:GetCommit
              - codecommit:GetUploadArchiveStatus
              - codecommit:UploadArchive
            Resource:
              - Fn::GetAtt: CodeCommitRepository.Arn
          - Sid: CodeBuildAccess
            Effect: Allow
            Action:
              - codebuild:StartBuild
              - codebuild:BatchGetBuilds
            Resource:
              - Fn::GetAtt: BuildProject.Arn
              - Fn::GetAtt: UnitTestProject.Arn
              - Fn::GetAtt: IntegrationTestProject.Arn
          - Sid: CloudFormationAccess
            Effect: Allow
            Action:
              - cloudformation:CreateStack
              - cloudformation:DeleteStack
              - cloudformation:DescribeStacks
              - cloudformation:UpdateStack
              - cloudformation:CreateChangeSet
              - cloudformation:DeleteChangeSet
              - cloudformation:DescribeChangeSet
              - cloudformation:ExecuteChangeSet
              - cloudformation:SetStackPolicy
              - cloudformation:ValidateTemplate
            Resource: "*"
          - Sid: IAMPassRolePermission
            Effect: Allow
            Action:
              - iam:PassRole
            Resource: "*"
            Condition:
              StringEqualsIfExists:
                iam:PassedToService:
                  - cloudformation.amazonaws.com

  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${ProjectName}-CodePipelineServiceRole-${AWS::Region}
      Description: Service role for CodePipeline
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - Ref: CodePipelineExecutionPolicy

  Pipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name:
        Ref: ProjectName
      RoleArn:
        Fn::GetAtt: CodePipelineServiceRole.Arn
      ArtifactStore:
        Location:
          Ref: ArtifactsBucket
        Type: S3
      RestartExecutionOnUpdate: true
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: 1
              Configuration:
                BranchName:
                  Ref: DeploymentBranch
                RepositoryName:
                  Fn::GetAtt: CodeCommitRepository.Name
                PollForSourceChanges: false
              OutputArtifacts:
                - Name: SourceCode
              RunOrder: 1

        - Name: DeployCICD
          Actions:
            - Name: DeployCICD
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName:
                  Fn::Sub: ${ProjectName}-cicd
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                RoleArn:
                  Fn::GetAtt: CloudFormationServiceRole.Arn
                TemplatePath:
                  Fn::Sub: SourceCode::cicd-template.yml
              InputArtifacts:
                - Name: SourceCode
              RunOrder: 1

        - Name: UnitTest
          Actions:
            - Name: UnitTest
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName:
                  Ref: UnitTestProject
              InputArtifacts:
                - Name: SourceCode
              OutputArtifacts:
                - Name: UnitTestReport
              RunOrder: 1

        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName:
                  Ref: BuildProject
              InputArtifacts:
                - Name: SourceCode
              OutputArtifacts:
                - Name: BuildArtifacts
              RunOrder: 1

        - Name: Deploy
          Actions:
            - Name: Deploy
              Namespace: Deploy
              ActionTypeId:
                Category: Deploy
                Owner: AWS
                Provider: CloudFormation
                Version: 1
              Configuration:
                ActionMode: CREATE_UPDATE
                StackName:
                  Ref: ProjectName
                Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
                RoleArn:
                  Fn::GetAtt: CloudFormationServiceRole.Arn
                TemplatePath:
                  Fn::Sub: BuildArtifacts::${PackagedTemplatePath}
                TemplateConfiguration:
                  Fn::Sub: BuildArtifacts::${TemplateConfigurationPath}
              InputArtifacts:
                - Name: BuildArtifacts
              RunOrder: 1

        - Name: IntegrationTest
          Actions:
            - Name: IntegrationTest
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: 1
              Configuration:
                ProjectName:
                  Ref: IntegrationTestProject
                EnvironmentVariables: |
                  [
                    {
                      "name": "REST_API_URL",
                      "value": "#{Deploy.RestApiUrl}"
                    },
                    {
                      "name": "MY_BUCKET",
                      "value": "#{Deploy.MyBucket}"
                    },
                    {
                      "name": "TODO_TABLE",
                      "value": "#{Deploy.TodoTable}"
                    }
                  ]
              InputArtifacts:
                - Name: SourceCode
              OutputArtifacts:
                - Name: IntegrationTestReport
              RunOrder: 1

  # SNS
  CodeCommitUpdateTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName:
        Fn::Sub: ${ProjectName}-CodeCommitUpdateTopic
      FifoTopic: false

  # Lambda
  StartPipelineFunctionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName:
        Fn::Sub: ${ProjectName}-StartPipelineFunctionPolicy-${AWS::Region}
      Description: Policy for StartPipelineFunction
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: StartPipelinePermission
            Effect: Allow
            Action:
              - codepipeline:StartPipelineExecution
            Resource:
              - Fn::Sub: arn:${AWS::Partition}:codepipeline:${AWS::Region}:${AWS::AccountId}:${Pipeline}

  StartPipelineFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${ProjectName}-StartPipelineFunctionRole-${AWS::Region}
      Description: Service role for StartPipelineFunction
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - Ref: StartPipelineFunctionPolicy

  StartPipelineFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${ProjectName}-StartPipelineFunction
      Description: Start pipeline function
      Role:
        Fn::GetAtt: StartPipelineFunctionRole.Arn
      Architectures:
        - arm64
      Runtime: nodejs18.x
      Handler: index.handler
      Environment:
        Variables:
          PIPELINE_NAME:
            Ref: Pipeline
      Events:
        SNSEvent:
          Type: SNS
          Properties:
            Topic:
              Ref: CodeCommitUpdateTopic
      InlineCode: |
        const {
          CodePipelineClient,
          StartPipelineExecutionCommand,
        } = require("@aws-sdk/client-codepipeline");

        exports.handler = async () => {
          const client = new CodePipelineClient({});
          const command = new StartPipelineExecutionCommand({
            name: process.env.PIPELINE_NAME,
          });
          const response = await client.send(command);
          console.log(`Pipeline started: (${response.pipelineExecutionId})`);
        };

  StartPipelineFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${StartPipelineFunction}

Outputs:
  CodeCommitRepositoryCloneUrlHttp:
    Value:
      Fn::GetAtt: CodeCommitRepository.CloneUrlHttp

  CodeCommitRepositoryCloneUrlSsh:
    Value:
      Fn::GetAtt: CodeCommitRepository.CloneUrlSsh
