# codepipeline/templates/demobucket-example.yml
AWSTemplateFormatVersion: "2010-09-09"
Description: Simple S3 bucket pipeline

Parameters:
  ApplicationName:
    Type: String
    Description: CodeDeploy application name
    Default: MyDemoApplication

  DeploymentGroupName:
    Type: String
    Description: Deployment group name
    Default: MyDemoDeploymentGroup

  CreateDeployment:
    Type: String
    Description: Ready to create deployment (must be false on stack creation)
    Default: "false"
    AllowedValues:
      - "false"
      - "true"

  InstanceType:
    Type: String
    Description: EC2 instance type
    Default: t2.micro
    AllowedValues:
      - t2.micro

  PublicKeyBody:
    Type: String
    Description: EC2 public key
    AllowedPattern: ssh-rsa .*

  IngressCidr:
    Type: String
    Description: IP address for ingress
    Default: 0.0.0.0/0
    AllowedPattern: \d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}/\d{1,2}
    ConstraintDescription: must be a valid IP CIDR range of the form x.x.x.x/x

  Ec2InstanceName:
    Type: String
    Description: Name for the EC2 instance
    Default: MyCodePipelineDemo

Conditions:
  DeploymentReady:
    Fn::Equals:
      - Ref: CreateDeployment
      - "true"

Mappings:
  ImageIdMapping:
    ap-northeast-1:
      Linux: ami-030cf0a1edb8636ab
      Windows: ami-0500753a8b9c3c925

Resources:
  DemoBucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled

  CodeDeployRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: codedeploy.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: Execution role for AWS CodeDeploy
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole

  CodeDeployApplication:
    Type: AWS::CodeDeploy::Application
    Properties:
      ApplicationName:
        Ref: ApplicationName
      ComputePlatform: Server

  MyDeploymentGroup:
    Type: AWS::CodeDeploy::DeploymentGroup
    Properties:
      ApplicationName:
        Ref: CodeDeployApplication
      Deployment:
        Fn::If:
          - DeploymentReady
          - Description: Deployment for WordPress app
            Revision:
              RevisionType: S3
              S3Location:
                Bucket:
                  Ref: DemoBucket
                BundleType: zip
                Key:
                  Ref: RevisionS3Key
          - Ref: AWS::NoValue
      DeploymentConfigName: CodeDeployDefault.OneAtATime
      DeploymentGroupName:
        Ref: DeploymentGroupName
      DeploymentStyle:
        DeploymentOption: WITHOUT_TRAFFIC_CONTROL
        DeploymentType: IN_PLACE
      Ec2TagFilters:
        - Key: Name
          Value:
            Ref: Ec2InstanceName
          Type: KEY_AND_VALUE
      ServiceRoleArn:
        Fn::GetAtt: CodeDeployRole.Arn

  MyKeyPair:
    Type: AWS::EC2::KeyPair
    Properties:
      KeyName:
        Fn::Sub: ${AWS::StackName}-keypair
      PublicKeyMaterial:
        Ref: PublicKeyBody

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription:
        Fn::Sub: Security group for ${AWS::StackName} stack
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp:
            Ref: IngressCidr
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp:
            Ref: IngressCidr

  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: Execution role for EC2 instance
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonEC2RoleforAWSCodeDeploy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: EC2InstanceRole

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId:
        Fn::FindInMap:
          - ImageIdMapping
          - Ref: AWS::Region
          - Linux
      InstanceType:
        Ref: InstanceType
      KeyName:
        Ref: MyKeyPair
      SecurityGroups:
        - Ref: MySecurityGroup
      Tags:
        - Key: Name
          Value:
            Ref: Ec2InstanceName
      IamInstanceProfile:
        Ref: EC2InstanceProfile

Outputs:
  DemoBucketName:
    Value:
      Ref: DemoBucket
