# rds/templates/postgresql-tutorial.yml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: LAMP server with RDS

Parameters:
  DBUser:
    Type: String
    Description: DB user
    Default: admin

  DBPassword:
    Type: String
    Description: DB password
    Default: password

  DBName:
    Type: String
    Description: DB name
    Default: sample

Mappings:
  RegionProfile2AMI:
    ap-northeast-1:
      AL2023: ami-067871d950411e643

  RegionProfile2Type:
    ap-northeast-1:
      AL2023: t2.micro

  Region2DefaultVPC:
    ap-northeast-1:
      VPC: vpc-01d5cfd2cad5314f1
      Subnet: subnet-00ee516fa04d610fe
      Subnet2: subnet-0c99e2001f0ae6c0a
      Subnet3: subnet-0deeda0e1c6cd4ffa
      PrivateSubnetCidr: 172.31.128.0/20
      PrivateSubnet2Cidr: 172.31.144.0/20

Resources:
  # VPC
  PrivateSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock:
        Fn::FindInMap:
          - Region2DefaultVPC
          - Ref: AWS::Region
          - PrivateSubnetCidr
      VpcId:
        Fn::FindInMap:
          - Region2DefaultVPC
          - Ref: AWS::Region
          - VPC
      AvailabilityZone:
        Fn::Select:
          - 0
          - Fn::GetAZs: ""
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${AWS::StackName}-pvsn

  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock:
        Fn::FindInMap:
          - Region2DefaultVPC
          - Ref: AWS::Region
          - PrivateSubnet2Cidr
      VpcId:
        Fn::FindInMap:
          - Region2DefaultVPC
          - Ref: AWS::Region
          - VPC
      AvailabilityZone:
        Fn::Select:
          - 1
          - Fn::GetAZs: ""
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${AWS::StackName}-pvsn

  PrivateRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:
        Fn::FindInMap:
          - Region2DefaultVPC
          - Ref: AWS::Region
          - VPC
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${AWS::StackName}-pvrtb

  PrivateSubnetPrivateRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PrivateSubnet
      RouteTableId:
        Ref: PrivateRouteTable

  PrivateSubnet2PrivateRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: PrivateSubnet2
      RouteTableId:
        Ref: PrivateRouteTable

  # EC2
  EC2SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName:
        Fn::Sub: ${AWS::StackName}-EC2SecurityGroup
      GroupDescription: Web security group
      VpcId:
        Fn::FindInMap:
          - Region2DefaultVPC
          - Ref: AWS::Region
          - VPC
      SecurityGroupIngress:
        - Description: HTTP inbound rule
          IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${AWS::StackName}-sg-ec2

  EC2InstanceRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${AWS::StackName}-EC2InstanceRole
      Description: Service role for EC2 instance
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  EC2InstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - Ref: EC2InstanceRole

  EC2LaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Metadata:
      AWS::CloudFormation::Init:
        config:
          files:
            /var/www/inc/dbinfo.inc:
              content:
                Fn::Sub: |
                  <?php
                    define("DB_SERVER", "${DBInstance.Endpoint.Address}");
                    define("DB_USERNAME", "${DBUser}");
                    define("DB_PASSWORD", "${DBPassword}");
                    define("DB_DATABASE", "${DBName}");
                  ?>
              mode: "000644"
            /var/www/html/SamplePage.php:
              content: |
                <?php include "../inc/dbinfo.inc"; ?>
                <html>
                  <body>
                    <h1>Sample page</h1>
                    <?php
                      /* Connect to MySQL and select the database. */
                      $connection = mysqli_connect(DB_SERVER, DB_USERNAME, DB_PASSWORD);

                      if (mysqli_connect_errno()) {
                        echo "Failed to connect to MySQL: " . mysqli_connect_error();
                      }

                      $database = mysqli_select_db($connection, DB_DATABASE);

                      /* Ensure that the EMPLOYEES table exists. */
                      VerifyEmployeesTable($connection, DB_DATABASE);

                      /* If input fields are populated, add a row to the EMPLOYEES table. */
                      $employee_name = htmlentities($_POST["NAME"]);
                      $employee_address = htmlentities($_POST["ADDRESS"]);

                      if (strlen($employee_name) || strlen($employee_address)) {
                        AddEmployee($connection, $employee_name, $employee_address);
                      }
                    ?>

                    <!-- Input form -->
                    <form action="<?PHP echo $_SERVER['SCRIPT_NAME'] ?>" method="POST">
                      <table border="0">
                        <tr>
                          <td>NAME</td>
                          <td>ADDRESS</td>
                        </tr>
                        <tr>
                          <td>
                            <input type="text" name="NAME" maxlength="45" size="30" />
                          </td>
                          <td>
                            <input type="text" name="ADDRESS" maxlength="90" size="60" />
                          </td>
                          <td>
                            <input type="submit" value="Add Data" />
                          </td>
                        </tr>
                      </table>
                    </form>

                    <!-- Display table data. -->
                    <table border="1" cellpadding="2" cellspacing="2">
                      <tr>
                        <td>ID</td>
                        <td>NAME</td>
                        <td>ADDRESS</td>
                      </tr>
                      <?php
                        $result = mysqli_query($connection, "SELECT * FROM EMPLOYEES");
                        while ($query_data = mysqli_fetch_row($result)) {
                          echo "<tr>";
                          echo "<td>", $query_data[0], "</td>",
                            "<td>", $query_data[1], "</td>",
                            "<td>", $query_data[2], "</td>";
                          echo "</tr>";
                        }
                      ?>
                    </table>

                    <!-- Clean up. -->
                    <?php
                      mysqli_free_result($result);
                      mysqli_close($connection);
                    ?>
                  </body>
                </html>

                <?php
                  /* Add an employee to the table. */
                  function AddEmployee($connection, $name, $address) {
                    $n = mysqli_real_escape_string($connection, $name);
                    $a = mysqli_real_escape_string($connection, $address);

                    $query = "INSERT INTO EMPLOYEES (NAME, ADDRESS) VALUES ('$n', '$a');";

                    if (!mysqli_query($connection, $query)) {
                      echo("<p>Error adding employee data.</p>");
                    }
                  }

                  /* Check whether the table exists and, if not, create it. */
                  function VerifyEmployeesTable($connection, $dbName) {
                    if (!TableExists("EMPLOYEES", $connection, $dbName)) {
                      $query = "CREATE TABLE EMPLOYEES (
                        ID int(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
                        NAME VARCHAR(45),
                        ADDRESS VARCHAR(90)
                      )";

                      if (!mysqli_query($connection, $query)) {
                        echo("<p>Error creating table.</p>");
                      }
                    }
                  }

                  /* Check for the existence of a table. */
                  function TableExists($tableName, $connection, $dbName) {
                    $t = mysqli_real_escape_string($connection, $tableName);
                    $d = mysqli_real_escape_string($connection, $dbName);

                    $query = "SELECT TABLE_NAME FROM information_schema.TABLES WHERE TABLE_NAME = '$t' AND TABLE_SCHEMA = '$d'";
                    $checktable = mysqli_query($connection, $query);

                    if (mysqli_num_rows($checktable) > 0) {
                      return true;
                    }
                    return false;
                  }
                ?>
              mode: "000644"
    Properties:
      LaunchTemplateName:
        Fn::Sub: ${AWS::StackName}-EC2LaunchTemplate
      VersionDescription: Launch template for EC2 instances
      TagSpecifications:
        - ResourceType: launch-template
          Tags:
            - Key: Name
              Value:
                Fn::Sub: ${AWS::StackName}-lt
      LaunchTemplateData:
        ImageId:
          Fn::FindInMap:
            - RegionProfile2AMI
            - Ref: AWS::Region
            - AL2023
        InstanceType:
          Fn::FindInMap:
            - RegionProfile2Type
            - Ref: AWS::Region
            - AL2023
        IamInstanceProfile:
          Name:
            Ref: EC2InstanceProfile
        SecurityGroupIds:
          - Ref: EC2SecurityGroup
        TagSpecifications:
          - ResourceType: instance
            Tags:
              - Key: Name
                Value:
                  Fn::Sub: ${AWS::StackName}-i
        UserData:
          Fn::Base64:
            Fn::Sub: |
              #!/bin/sh
              dnf update -y
              dnf install -y httpd php php-mysqli mariadb105
              systemctl start httpd
              systemctl enable httpd
              /opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource EC2LaunchTemplate --region ${AWS::Region}
              usermod -a -G apache ec2-user
              chown -R ec2-user:apache /var/www
              chmod 2775 /var/www
              find /var/www -type d -exec chmod 2775 {} \;
              find /var/www -type f -exec chmod 0664 {} \;

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      LaunchTemplate:
        LaunchTemplateId:
          Ref: EC2LaunchTemplate
        Version:
          Fn::GetAtt: EC2LaunchTemplate.LatestVersionNumber

  # RDS
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName:
        Fn::Sub: ${AWS::StackName}-DBSecurityGroup
      GroupDescription: DB security group
      VpcId:
        Fn::FindInMap:
          - Region2DefaultVPC
          - Ref: AWS::Region
          - VPC
      SecurityGroupIngress:
        - Description: DB inbound rule
          IpProtocol: tcp
          FromPort: 3306
          ToPort: 3306
          SourceSecurityGroupId:
            Ref: EC2SecurityGroup
      Tags:
        - Key: Name
          Value:
            Fn::Sub: ${AWS::StackName}-sg-db

  DBSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupName:
        Fn::Sub: ${AWS::StackName}-DBSubnetGroup
      DBSubnetGroupDescription: DB subnet group
      SubnetIds:
        - Ref: PrivateSubnet
        - Ref: PrivateSubnet2

  DBInstance:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Delete
    UpdateReplacePolicy: Delete
    Properties:
      DBInstanceIdentifier:
        Fn::Sub: ${AWS::StackName}-DBInstance
      Engine: mysql
      EngineVersion: 8.0
      MasterUsername:
        Ref: DBUser
      MasterUserPassword:
        Ref: DBPassword
      Port: 3306
      DBName:
        Ref: DBName
      DBInstanceClass: db.t3.micro
      StorageType: gp2
      AllocatedStorage: 20
      MaxAllocatedStorage: 100
      StorageEncrypted: true
      BackupRetentionPeriod: 0
      NetworkType: IPV4
      DBSubnetGroupName:
        Ref: DBSubnetGroup
      VPCSecurityGroups:
        - Ref: DBSecurityGroup

Outputs:
  DBHost:
    Description: DB instance host
    Value:
      Fn::GetAtt: DBInstance.Endpoint.Address

  DBPort:
    Description: DB instance port
    Value:
      Fn::GetAtt: DBInstance.Endpoint.Port
