# secretsmanager/templates/api-key-secret.yml
AWSTemplateFormatVersion: "2010-09-09"
Description: API key secret stack
Resources:
  ApiKeySecret:
    Type: AWS::SecretsManager::Secret
    Properties:
      Description: API key secret
      SecretString: |
        {
          "APIKEY": "keyboard cat"
        }

  TodoBucket:
    Type: AWS::S3::Bucket
