# apigateway/templates/lambda-proxy-api.yml
AWSTemplateFormatVersion: "2010-09-09"
Description: Lambda proxy API stack

Parameters:
  StageName:
    Type: String
    Description: API Gateway deployment stage
    Default: dev
    AllowedValues: [dev, prod]

Resources:
  LambdaFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${AWS::StackName}-LambdaFunctionExecutionRole-${AWS::Region}
      Description: Execution role for Lambda Function
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                Fn::Sub: lambda.${AWS::URLSuffix}
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  GreetingFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${AWS::StackName}-GreetingFunction

  GreetingFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName:
        Fn::Sub: ${AWS::StackName}-GreetingFunction
      Description: Greeting Function
      Role:
        Fn::GetAtt: LambdaFunctionExecutionRole.Arn
      Handler: index.handler
      Runtime: nodejs16.x
      Architectures:
        - x86_64
      LoggingConfig:
        LogGroup:
          Ref: GreetingFunctionLogGroup
      Code:
        ZipFile: |
          "use strict";
          console.log("Loading hello world function");

          exports.handler = async event => {
            let name = "you";
            let city = "World";
            let time = "day";
            let day = "";
            let responseCode = 200;
            console.log("request: " + JSON.stringify(event));

            if (event.queryStringParameters && event.queryStringParameters.name) {
              console.log("Received name: " + event.queryStringParameters.name);
              name = event.queryStringParameters.name;
            }

            if (event.queryStringParameters && event.queryStringParameters.city) {
              console.log("Received city: " + event.queryStringParameters.city);
              city = event.queryStringParameters.city;
            }

            if (event.headers && event.headers["day"]) {
              console.log("Received day: " + event.headers.day);
              day = event.headers.day;
            }

            if (event.body) {
              let body = JSON.parse(event.body);
              if (body.time) time = body.time;
            }

            let greeting = `Good ${time}, ${name} of ${city}.`;
            if (day) greeting += ` Happy ${day}!`;

            let responseBody = {
              message: greeting,
              input: event,
            };

            // The output from a Lambda proxy integration must be
            // in the following JSON object. The 'headers' property
            // is for custom response headers in addition to standard
            // ones. The 'body' property must be a JSON string. For
            // base64-encoded payload, you must also set the 'isBase64Encoded'
            // property to 'true'.
            let response = {
              statusCode: responseCode,
              headers: {
                "x-custom-header": "my custom header value",
              },
              body: JSON.stringify(responseBody),
            };
            console.log("response: " + JSON.stringify(response));
            return response;
          };

  GreetingFunctionPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName:
        Ref: GreetingFunction
      Principal:
        Fn::Sub: apigateway.${AWS::URLSuffix}

  LambdaProxyApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: Lambda Proxy API
      EndpointConfiguration:
        Types:
          - REGIONAL
      Name: LambdaProxyApi
      Body:
        openapi: "3.0.1"
        info:
          version: "1.0"
        paths:
          /helloworld:
            x-amazon-apigateway-any-method:
              operationId: AnyHelloworld
              x-amazon-apigateway-integration:
                type: aws_proxy
                uri:
                  Fn::Sub: arn:${AWS::Partition}:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${GreetingFunction.Arn}/invocations
                httpMethod: POST

  LambdaProxyApiDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      Description:
        Fn::Sub: Lambda Proxy API ${StageName} deployment
      RestApiId:
        Ref: LambdaProxyApi
      StageDescription:
        Description:
          Fn::Sub: Lambda Proxy API ${StageName} stage
      StageName:
        Ref: StageName

Outputs:
  LambdaProxyApiTestUrl:
    Value:
      Fn::Sub: https://${LambdaProxyApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/${StageName}
