# sqs/templates/first-DeadLetterQueue.yml
AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: My first dead-letter queue

Resources:
  DeadLetterQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        Fn::Sub: ${AWS::StackName}-DeadLetterQueue

  SourceQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName:
        Fn::Sub: ${AWS::StackName}-SourceQueue
      ReceiveMessageWaitTimeSeconds: 1
      VisibilityTimeout: 5
      RedrivePolicy:
        deadLetterTargetArn:
          Fn::GetAtt: DeadLetterQueue.Arn
        maxReceiveCount: 2

  ProducerFunctionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName:
        Fn::Sub: ${AWS::StackName}-ProducerFunctionPolicy-${AWS::Region}
      Description: Policy for ProducerFunction
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - sqs:SendMessage
            Resource:
              - Fn::GetAtt: SourceQueue.Arn

  ProducerFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${AWS::StackName}-ProducerFunctionRole-${AWS::Region}
      Description: Service role for ProducerFunction
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - Ref: ProducerFunctionPolicy

  ProducerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${AWS::StackName}-ProducerFunction
      Description: Push messages into Queue
      Role:
        Fn::GetAtt: ProducerFunctionRole.Arn
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - arm64
      Environment:
        Variables:
          QUEUE_URL:
            Ref: SourceQueue
      InlineCode: |
        const { SendMessageCommand, SQSClient } = require("@aws-sdk/client-sqs");

        exports.handler = async () => {
          const client = new SQSClient();
          const message = new Date().toISOString();
          const command = new SendMessageCommand({
            MessageBody: message,
            QueueUrl: process.env.QUEUE_URL,
          });
          const { MessageId, SequenceNumber } = await client.send(command);
          const result = { MessageId, SequenceNumber };
          console.log(JSON.stringify(result, null, 2));
          return result;
        };

  ProducerFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${ProducerFunction}

  ConsumerFunctionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName:
        Fn::Sub: ${AWS::StackName}-ConsumerFunctionPolicy-${AWS::Region}
      Description: Policy for ConsumerFunction
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - sqs:DeleteMessage
              - sqs:ReceiveMessage
            Resource:
              - Fn::GetAtt: SourceQueue.Arn

  ConsumerFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${AWS::StackName}-ConsumerFunctionRole-${AWS::Region}
      Description: Service role for ConsumerFunction
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - Ref: ConsumerFunctionPolicy

  ConsumerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName:
        Fn::Sub: ${AWS::StackName}-ConsumerFunction
      Description: Consumer function for Queue
      Role:
        Fn::GetAtt: ConsumerFunctionRole.Arn
      Handler: index.handler
      Runtime: nodejs18.x
      Architectures:
        - arm64
      Environment:
        Variables:
          QUEUE_URL:
            Ref: SourceQueue
      InlineCode: |
        const {
          DeleteMessageCommand,
          ReceiveMessageCommand,
          SQSClient,
        } = require("@aws-sdk/client-sqs");

        exports.handler = async () => {
          const QueueUrl = process.env.QUEUE_URL;
          const client = new SQSClient();
          const command = new ReceiveMessageCommand({ QueueUrl });
          const { Messages = [] } = await client.send(command);
          const randInt = new Date().getUTCMilliseconds();
          if (randInt % 3 === 0) {
            const promises = Messages.map(async ({ Body, ReceiptHandle }) => {
              console.log(Body);
              const command = new DeleteMessageCommand({ QueueUrl, ReceiptHandle });
              await client.send(command);
            });
            await Promise.all(promises);
          }
          return Messages;
        };

  ConsumerFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${ConsumerFunction}
