# sfn/templates/resultpath-demo.yml
AWSTemplateFormatVersion: "2010-09-09"
Description: Activity and state machine

Resources:
  StateMachineExecutionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName:
        Fn::Sub: ${AWS::StackName}-StateMachineExecutionPolicy-${AWS::Region}
      Description: Execution policy for State Machine
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - xray:PutTraceSegments
              - xray:PutTelemetryRecords
              - xray:GetSamplingRules
              - xray:GetSamplingTargets
            Resource:
              - "*"

  StateMachineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${AWS::StackName}-StateMachineExecutionRole-${AWS::Region}
      Description: Execution role for State Machine
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                Fn::Sub: states.${AWS::URLSuffix}
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - Ref: StateMachineExecutionPolicy

  GetGreetingActivity:
    Type: AWS::StepFunctions::Activity
    Properties:
      Name: GetGreeting

  ActivityStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      Definition:
        Comment: An example using a Task state.
        StartAt: getGreeting
        Version: "1.0"
        TimeoutSeconds: 300
        States:
          getGreeting:
            Type: Task
            Resource:
              Ref: GetGreetingActivity
            End: true
      RoleArn:
        Fn::GetAtt: StateMachineExecutionRole.Arn
      StateMachineType: STANDARD

Outputs:
  GetGreetingActivityArn:
    Value:
      Ref: GetGreetingActivity

  ActivityStateMachineArn:
    Value:
      Ref: ActivityStateMachine
