# sfn/templates/execution-api-gateway.yml
AWSTemplateFormatVersion: "2010-09-09"
Description: Execute Step Function from API Gateway

Resources:
  StateMachineExecutionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName:
        Fn::Sub: ${AWS::StackName}-StateMachineExecutionPolicy-${AWS::Region}
      Description: Execution policy for State Machine
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - xray:PutTraceSegments
              - xray:PutTelemetryRecords
              - xray:GetSamplingRules
              - xray:GetSamplingTargets
            Resource:
              - "*"

  StateMachineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${AWS::StackName}-StateMachineExecutionRole-${AWS::Region}
      Description: Execution role for State Machine
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - Ref: StateMachineExecutionPolicy

  HelloWorldStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      Definition:
        Comment: A Hello World example of the Amazon States Language using Pass states
        StartAt: Hello
        States:
          Hello:
            Type: Pass
            Next: World
          World:
            Type: Pass
            Result: World
            End: true
      RoleArn:
        Fn::GetAtt: StateMachineExecutionRole.Arn
      StateMachineType: STANDARD

  APIGatewayExecutionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName:
        Fn::Sub: ${AWS::StackName}-APIGatewayExecutionPolicy-${AWS::Region}
      Description: Execution policy for API Gateway
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - states:DescribeExecution
              - states:StartExecution
            Resource:
              - "*"

  APIGatewayExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${AWS::StackName}-APIGatewayExecutionRole-${AWS::Region}
      Description: Execution role for API Gateway
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: apigateway.amazonaws.com
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/service-role/AmazonAPIGatewayPushToCloudWatchLogs
        - Ref: APIGatewayExecutionPolicy

  StartExecutionApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Description: StartExecution API
      EndpointConfiguration:
        Types: [REGIONAL]
      Name: StartExecutionAPI

  ExecutionResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      ParentId:
        Fn::GetAtt: StartExecutionApi.RootResourceId
      PathPart: execution
      RestApiId:
        Ref: StartExecutionApi

  PostExecutionMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      AuthorizationType: NONE
      HttpMethod: POST
      Integration:
        Credentials:
          Fn::GetAtt: APIGatewayExecutionRole.Arn
        IntegrationHttpMethod: POST
        IntegrationResponses:
          - SelectionPattern: 200
            StatusCode: 200
        Type: AWS
        Uri:
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:states:action/StartExecution
      MethodResponses:
        - ResponseModels:
            application/json: Empty
          StatusCode: 200
      OperationName: PostExecution
      ResourceId:
        Ref: ExecutionResource
      RestApiId:
        Ref: StartExecutionApi

  StartExecutionDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn:
      - PostExecutionMethod
    Properties:
      Description: StartExecution API deployment
      RestApiId:
        Ref: StartExecutionApi
      StageDescription:
        Description: StartExecution API test stage
      StageName: test

Outputs:
  HelloWorldStateMachineArn:
    Value:
      Ref: HelloWorldStateMachine

  StateMachineExecutionRoleArn:
    Value:
      Fn::GetAtt: StateMachineExecutionRole.Arn

  APIGatewayExecutionRoleArn:
    Value:
      Fn::GetAtt: APIGatewayExecutionRole.Arn

  StartExecutionApiTestUrl:
    Value:
      Fn::Sub: https://${StartExecutionApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/test
