# sfn/templates/map-lambda.yml
AWSTemplateFormatVersion: "2010-09-09"
Description: State machine with a Map state

Resources:
  LambdaFunctionExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${AWS::StackName}-LambdaFunctionExecutionRole-${AWS::Region}
      Description: Execution role for Lambda Function
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                Fn::Sub: lambda.${AWS::URLSuffix}
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - Fn::Sub: arn:${AWS::Partition}:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  HelloFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName:
        Fn::Sub: /aws/lambda/${AWS::StackName}-HelloFunction

  HelloFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName:
        Fn::Sub: ${AWS::StackName}-HelloFunction
      Description: Lambda function returns a greeting message
      Role:
        Fn::GetAtt: LambdaFunctionExecutionRole.Arn
      Handler: index.handler
      Runtime: nodejs14.x
      Architectures:
        - x86_64
      LoggingConfig:
        LogGroup:
          Ref: HelloFunctionLogGroup
      Code:
        ZipFile: |
          exports.handler = (event, context, callback) => {
            callback(null, "Hello from " + event.who + "!");
          };

  StateMachineExecutionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName:
        Fn::Sub: ${AWS::StackName}-StateMachineExecutionPolicy-${AWS::Region}
      Description: Execution policy for State Machine
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action:
              - xray:PutTraceSegments
              - xray:PutTelemetryRecords
              - xray:GetSamplingRules
              - xray:GetSamplingTargets
            Resource:
              - "*"
          - Effect: Allow
            Action:
              - lambda:InvokeFunction
            Resource:
              - "*"

  StateMachineExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName:
        Fn::Sub: ${AWS::StackName}-StateMachineExecutionRole-${AWS::Region}
      Description: Execution role for State Machine
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                Fn::Sub: states.${AWS::URLSuffix}
            Action:
              - sts:AssumeRole
      ManagedPolicyArns:
        - Ref: StateMachineExecutionPolicy

  MapLambdaStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      Definition:
        Comment: State machine with a Map state
        StartAt: ExampleMapState
        States:
          ExampleMapState:
            Type: Map
            Iterator:
              StartAt: CallLambda
              States:
                CallLambda:
                  Type: Task
                  Resource:
                    Fn::GetAtt: HelloFunction.Arn
                  End: true
            End: true
      RoleArn:
        Fn::GetAtt: StateMachineExecutionRole.Arn
      StateMachineType: STANDARD

Outputs:
  LambdaFunctionExecutionRoleArn:
    Value:
      Fn::GetAtt: LambdaFunctionExecutionRole.Arn

  HelloFunctionArn:
    Value:
      Fn::GetAtt: HelloFunction.Arn

  StateMachineExecutionRoleArn:
    Value:
      Fn::GetAtt: StateMachineExecutionRole.Arn

  MapLambdaStateMachineArn:
    Value:
      Ref: MapLambdaStateMachine
