# appsync/templates/dynamodb-data-source.yml
AWSTemplateFormatVersion: "2010-09-09"
Description: DynamoDB data source example

Resources:
  DynamoDBDataSourceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: CRUD role for DynamoDB data source
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess

  TodoTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  CommentTable:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions:
        - AttributeName: todoid
          AttributeType: S
        - AttributeName: commentid
          AttributeType: S
      KeySchema:
        - AttributeName: todoid
          KeyType: HASH
        - AttributeName: commentid
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      GlobalSecondaryIndexes:
        - IndexName: todoid-index
          KeySchema:
            - AttributeName: todoid
              KeyType: HASH
          Projection:
            ProjectionType: ALL
          ProvisionedThroughput:
            ReadCapacityUnits: 5
            WriteCapacityUnits: 5

  GraphQLApiLoggingRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service: appsync.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: Logging role for GraphQl API
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSAppSyncPushToCloudWatchLogs

  GraphQLApi:
    Type: AWS::AppSync::GraphQLApi
    Properties:
      AuthenticationType: API_KEY
      Name:
        Ref: AWS::StackName
      LogConfig:
        CloudWatchLogsRoleArn:
          Fn::GetAtt: GraphQLApiLoggingRole.Arn
        ExcludeVerboseContent: true
        FieldLogLevel: ERROR

  GraphQLSchema:
    Type: AWS::AppSync::GraphQLSchema
    Properties:
      ApiId:
        Fn::GetAtt: GraphQLApi.ApiId
      Definition: |
        schema {
          query: Query
          mutation: Mutation
        }

        type Query {
          getTodos(limit: Int, nextToken: String): TodoConnection
        }

        type Mutation {
          addTodo(
            id: ID!
            name: String
            description: String
            priority: Int
            status: TodoStatus
          ): Todo
          addComment(todoid: ID!, content: String): Comment
        }

        type Comment {
          todoid: ID!
          commentid: String!
          content: String
        }

        type Todo {
          id: ID!
          name: String
          description: String
          priority: Int
          status: TodoStatus
          comments: [Comment]
        }

        type TodoConnection {
          todos: [Todo]
          nextToken: String
        }

        enum TodoStatus {
          done
          pending
        }

  GraphQLApiKey:
    Type: AWS::AppSync::ApiKey
    Properties:
      ApiId:
        Fn::GetAtt: GraphQLApi.ApiId
      Description: My GraphQl API key

  TodoTableDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId:
        Fn::GetAtt: GraphQLApi.ApiId
      Description: TodoTable data source
      Name: TodoTableDataSource
      Type: AMAZON_DYNAMODB
      ServiceRoleArn:
        Fn::GetAtt: DynamoDBDataSourceRole.Arn
      DynamoDBConfig:
        AwsRegion:
          Ref: AWS::Region
        TableName:
          Ref: TodoTable

  CommentTableDataSource:
    Type: AWS::AppSync::DataSource
    Properties:
      ApiId:
        Fn::GetAtt: GraphQLApi.ApiId
      Description: CommentTable data source
      Name: CommentTableDataSource
      Type: AMAZON_DYNAMODB
      ServiceRoleArn:
        Fn::GetAtt: DynamoDBDataSourceRole.Arn
      DynamoDBConfig:
        AwsRegion:
          Ref: AWS::Region
        TableName:
          Ref: CommentTable

  CreateTodoFunction:
    Type: AWS::AppSync::FunctionConfiguration
    Properties:
      ApiId:
        Fn::GetAtt: GraphQLApi.ApiId
      Name: CREATE_TODO
      Description: Create Todo function
      DataSourceName:
        Fn::GetAtt: TodoTableDataSource.Name
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: 1.0.0
      Code: |
        import { util } from "@aws-appsync/utils";

        /**
          * Sends a request to `put` an item in the DynamoDB data source
          */
        export function request(ctx) {
          const { id, ...values } = ctx.args;
          return {
            operation: "PutItem",
            key: util.dynamodb.toMapValues({ id }),
            attributeValues: util.dynamodb.toMapValues(values),
          };
        }

        /**
          * returns the result of the `put` operation
          */
        export function response(ctx) {
          return ctx.result;
        }

  ScanTodosFunction:
    Type: AWS::AppSync::FunctionConfiguration
    Properties:
      ApiId:
        Fn::GetAtt: GraphQLApi.ApiId
      Name: SCAN_TODOS
      Description: Scan Todos function
      DataSourceName:
        Fn::GetAtt: TodoTableDataSource.Name
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: 1.0.0
      Code: |
        import { util } from "@aws-appsync/utils";

        /**
         * Performs a scan on the dynamodb data source
         */
        export function request(ctx) {
          const { limit = 20, nextToken } = ctx.args;
          return { operation: "Scan", limit, nextToken };
        }

        /**
         * return a list of scanned todo items
         */
        export function response(ctx) {
          const { items: todos = [], nextToken } = ctx.result;
          return { todos, nextToken };
        }

  AddTodoResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::GetAtt: GraphQLApi.ApiId
      Kind: PIPELINE
      TypeName: Mutation
      FieldName: addTodo
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: 1.0.0
      Code: |
        export function request(ctx) {
          return {};
        }

        export function response(ctx) {
          return ctx.prev.result;
        }
      PipelineConfig:
        Functions:
          - Fn::GetAtt: CreateTodoFunction.FunctionId

  GetTodosResolver:
    Type: AWS::AppSync::Resolver
    Properties:
      ApiId:
        Fn::GetAtt: GraphQLApi.ApiId
      Kind: PIPELINE
      TypeName: Query
      FieldName: getTodos
      Runtime:
        Name: APPSYNC_JS
        RuntimeVersion: 1.0.0
      Code: |
        export function request(ctx) {
          return {};
        }

        export function response(ctx) {
          return ctx.prev.result;
        }
      PipelineConfig:
        Functions:
          - Fn::GetAtt: ScanTodosFunction.FunctionId

Outputs:
  GraphQLApiId:
    Value:
      Fn::GetAtt: GraphQLApi.ApiId

  GraphQLApiKey:
    Value:
      Fn::GetAtt: GraphQLApiKey.ApiKey
